# Generated by Django 4.2.2 on 2023-07-01 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='idDiscord',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='senha',
        ),
    ]
