# Generated by Django 4.2.2 on 2023-07-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_pessoa_email_remove_pessoa_iddiscord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='idDiscord',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
